config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  get "log-out" => "sessions#destroy", :as => "log-out"
  get "log-in" => "sessions#new", :as => "log-in"
  get "sign-up" => "users#new", :as => "sign-up"

  resources :posts do
  	resources :comments
  end
  
  resources :users
  resources :sessions
  root 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments #, inverse_of: :post
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  attr_accessor :category_id

  accepts_nested_attributes_for :comments, :user, :categories, :categorizations

  validates :title, :text, :user, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if params[:category]
      @categorizations = Categorization.where(' category_id = ? ', params[:category])
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    if @post == nil
      redirect_to root_url, notice: 'Post not found!'
    end

    @is_owner = if current_user and current_user.id == @post.user.id then
      true
    else
      false
    end
  end

  # GET /posts/new
  def new
    if current_user
      @post = Post.new
    else
      redirect_to root_url, notice: 'You cannot create post without be user'
    end
  end

  # GET /posts/1/edit
  def edit
    if current_user == nil
      redirect_to root_url, notice: 'You cannot edit this post'
    end

    if current_user and current_user.id != @post.user.id
      redirect_to root_url, notice: 'You cannot edit this post'
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.categories << Category.find(params[:post][:category_id])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if current_user and current_user.id == @post.user.id
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_url, notice: 'You cannot update this post'
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if current_user and current_user.id == @post.user.id
      @post.destroy
      redirect_to root_url, notice: 'Post destroyed'
    else
      redirect_to root_url, notice: 'You cannot destroy this post'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      begin
        @post = Post.find(params[:id])
      rescue
        logger.info('Post não encontrado')
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :text)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post, class: 'form-horizontal', html: { multipart: true } ) do |f| %>
  
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-sm-12">
    <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
  </div>
  <div class="from-group col-sm-12">
    <%= f.cktext_area :text, class: 'form-control' %>
  </div>
  <div class="form-group col-sm-4" style="margin: 10px auto;">
    <%= f.label "Category", class: 'control-label' %>
    <%= f.select :category_id, Category.all.map { |e| [e.kind, e.id] }, {}, {class: 'form-control'} %>
  </div>

  <div class="form-group col-sm-12" style="margin: 10px auto;">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
    
<% end %>

app/views/posts/_post.html.erb
<h2><%= link_to post.title, post %></h2>
<p class="lead">by <%= post.user.email %></p>
<p><span class="glyphicon glyphicon-time"></span>Criado em <%= post.created_at %></p>
<hr>
<p><%= truncate(strip_tags(post.text), length: 200) %></p>
<%= link_to 'Ler mais...', post %>

app/views/posts/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render @categorizations %>

app/views/posts/new.html.erb
<%= render 'form' %>	

app/views/posts/show.html.erb
<div class="page-header">
	<ul class="list-inline pull-right">
		<li><%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-warning' if @is_owner %></li>
		<li><%= link_to 'Back', root_path, class: 'btn btn-default' %></li>
	</ul>
	<h1><%= @post.title %></h1>
</div>

<%= @post.text.html_safe %>

<hr/>

<p>Created by: <kbd><%= @post.user.email %></kbd></p>
<p>
	Tags: 
<% @post.categories.each do |category| %>
	<kbd><%= category.kind %> </kbd> 
<% end %>
</p>


<hr/>

<%= render 'comments/form' %>

<hr/>

<%= render @post.comments %>