config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  get "log-out" => "sessions#destroy", :as => "log-out"
  get "log-in" => "sessions#new", :as => "log-in"
  get "sign-up" => "users#new", :as => "sign-up"

  resources :posts do
  	resources :comments
  end
  
  resources :users
  resources :sessions
  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="gt-ie8 gt-ie9 not-ie">
<head>
    
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>TCC</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

  <!-- Open Sans font from Google CDN -->
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin" rel="stylesheet" type="text/css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

  <%= yield :js %>
  <%= yield :css %>
  
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="#" class="navbar-brand">Blog</a>
        </div>

        <div class="collapse navbar-collapse" id="menu">
          <ul class="nav navbar-nav">
            <% Category.all.each do |category| %>
              <li>
                  <%= link_to category.kind, posts_path(category: category.id) %>
              </li>
            <% end %>
            <% if current_user %>
              <li><%= link_to 'Novo Post', new_post_path %></li>
            <% end %>
            <li><a href="#">Sobre</a></li>
          </ul>

          <ul class="nav navbar-nav pull-right">
            <li class="dropdown">
              <% if current_user %>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", user_path(current_user) %></li>
                  <li><%= link_to "Log out", log_out_path %></li>
                </ul>
              <% else %>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Entrar <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Sign up", sign_up_path %></li>
                  <li><%= link_to "log in", log_in_path %></li>
                </ul>
              <% end %>
            </li>
          </ul>
        </div>
      </div>  
    </nav>

    <div class="row">
      <div class="col-lg-8"><%= yield %></div>
      <div class="col-md-4">
        <div class="well">
          <h4>Pesquisar</h4>
          <div class="input-group">
            <input type="text" class="form-control">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">
                <span class="glyphicon glyphicon-search"></span>
              </button>
            </span>
          </div>
        </div>

        <div class="well">
          <h4>Categorias</h4>
          <div class="row">
            <div class="col-lg-6">
              <ul class="list-unstyled">
                <% Category.all.each do |category| %>
                  <li>
                    <%= link_to category.kind, posts_path(category: category.id) %>
                  </li>
                <% end %>
              </ul>
            </div>
            
          </div>
          <!-- /.row -->
        </div>

        <div class="well">
          <h4>Objetivos</h4>
          <p>Sistema feito para compartilhar comenhecimento a respeito de programação expecificamente nas linguagens Ruby, Python, Puppet e C/C++</p>
        </div>
      </div>
    </div>
        
  </div>
</body>
</html>

app/views/layouts/sign.html.erb
<!DOCTYPE html>
<html class="gt-ie8 gt-ie9 not-ie">
<head>
    
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>TCC</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

  <!-- Open Sans font from Google CDN -->
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin" rel="stylesheet" type="text/css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

  <%= yield :js %>
  <%= yield :css %>
  
</head>
<body>
  <div class="container">

    <div class="row" style="margin: 100px auto">
     <%= yield %>
    </div>
        
  </div>
</body>
</html>